#---------------------------------#
#      general configuration      #
#---------------------------------#

environment:
  nuget_api_key:
    secure: tFtdF2DZf/f0Mxvogpg+OAWtHnEK5ipIpru4Y5BFJDx1qBMi7asHrsWUPRrdlWLJ

# version format
version: 0.1.{build}

# Build worker image (VM template)
image: Visual Studio 2019

# clone directory
clone_folder: c:\projects\VL.Devices.AzureKinect

branches:
  only:
    - master

only_commits:
  message: /build/

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "0.1.{build}-alpha"
  assembly_file_version: "{version}"


install:
  - nuget sources add -Name vvvv -Source http://teamcity.vvvv.org/guestAuth/app/nuget/feed/_Root/default/v3/index.json
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - nuget pack appveyor\VL.Devices.AzureKinect.Body.nuspec -Version %APPVEYOR_BUILD_VERSION%-alpha
  - nuget setApiKey %nuget_api_key%
  - nuget push C:\projects\VL.Skia3d\VL.Devices.AzureKinect.Body.%APPVEYOR_BUILD_VERSION%-alpha.nupkg -Source https://api.nuget.org/v3/index.json
    
artifacts:
  - path: '*.nupkg'
    type: NuGetPackage
  
#---------------------------------#
#         notifications           #
#---------------------------------#

test: off

notifications:

  # Email
  - provider: Email
    to:
      - devvvvs@vvvv.org
    subject: 'VL.Devices.AzureKinect Build {{status}}'                  # optional
    message: "{{message}}, {{commitId}}, ..."    # optional
    on_build_status_changed: true